# Generated by Django 4.2.19 on 2026-03-24 03:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ea_exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ea_ebooks/')),
                ('external_url', models.URLField(blank=True, help_text='External link (IRS.gov, PDF CDN, etc.)')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='ea_exam.eapart')),
            ],
            options={
                'verbose_name': 'EA eBook',
                'ordering': ['part', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='Question / term')),
                ('back', models.TextField(help_text='Answer / definition')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.eadomain')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='ea_exam.eapart')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.eatopic')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'ordering': ['part', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='IRSPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('irs_url', models.URLField()),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('part', models.ForeignKey(blank=True, help_text='Primarily relevant EA Part', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.eapart')),
                ('topics', models.ManyToManyField(blank=True, to='ea_exam.eatopic')),
            ],
            options={
                'verbose_name': 'IRS Publication',
                'ordering': ['pub_number'],
            },
        ),
        migrations.CreateModel(
            name='EbookHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('selected_text', models.TextField()),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ea_content.eaebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EbookBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ea_content.eaebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EANote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_admin_note', models.BooleanField(default=True, help_text='Admin notes are visible to all students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.eadomain')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.eapart')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.eatopic')),
            ],
            options={
                'verbose_name': 'EA Note',
                'ordering': ['part', 'domain', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardSRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveSmallIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('next_review', models.DateField(default=datetime.date.today)),
                ('last_quality', models.PositiveSmallIntegerField(default=3)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ea_content.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flashcard SRS State',
                'unique_together': {('user', 'card')},
            },
        ),
        migrations.CreateModel(
            name='EbookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('pct_read', models.FloatField(default=0.0)),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ea_content.eaebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ebook')},
            },
        ),
    ]
