# Generated by Django 4.2.19 on 2026-03-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0001_initial'),
        ('ea_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='ea_videos/')),
                ('external_url', models.URLField(blank=True, help_text='YouTube/Vimeo link')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='ea_exam.eadomain')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ea_exam.eapart')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='ea_exam.eatopic')),
            ],
            options={
                'verbose_name': 'EA Video',
                'ordering': ['part', 'domain', 'topic', 'order'],
            },
        ),
    ]
