# Generated by Django 4.2.19 on 2026-03-25 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0003_userprogress'),
        ('ea_content', '0002_eavideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eaebook',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='ea_exam.eadomain'),
        ),
        migrations.AddField(
            model_name='eaebook',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='ea_exam.eatopic'),
        ),
    ]
