# Generated by Django 4.2.19 on 2026-03-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea_content', '0003_eaebook_domain_eaebook_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eavideo',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='eavideo',
            name='part',
        ),
        migrations.RemoveField(
            model_name='eavideo',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='ebookbookmark',
            name='ebook',
        ),
        migrations.RemoveField(
            model_name='ebookbookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ebookhighlight',
            name='ebook',
        ),
        migrations.RemoveField(
            model_name='ebookhighlight',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='ebookprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ebookprogress',
            name='ebook',
        ),
        migrations.RemoveField(
            model_name='ebookprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='irspublication',
            name='part',
        ),
        migrations.RemoveField(
            model_name='irspublication',
            name='topics',
        ),
        migrations.DeleteModel(
            name='EAEbook',
        ),
        migrations.DeleteModel(
            name='EAVideo',
        ),
        migrations.DeleteModel(
            name='EbookBookmark',
        ),
        migrations.DeleteModel(
            name='EbookHighlight',
        ),
        migrations.DeleteModel(
            name='EbookProgress',
        ),
        migrations.DeleteModel(
            name='IRSPublication',
        ),
    ]
