# Generated by Django 4.2.16 on 2026-06-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_content', '0004_remove_eavideo_domain_remove_eavideo_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('average', 'Average'), ('hard', 'Hard')], default='average', max_length=10),
        ),
    ]
