# Generated by Django 4.2.16 on 2026-08-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_promocode_invoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='utr_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lifetime',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Lifetime', 'Lifetime')], db_index=True, default='Lifetime', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
