# Generated by Django 4.2.16 on 2026-09-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_courseoffer_dep_head_delete_courseallocation_and_more'),
        ('core', '0004_blogarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
