# Generated by Django 4.2.16 on 2026-09-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffer',
            name='dep_head',
        ),
        migrations.DeleteModel(
            name='CourseAllocation',
        ),
        migrations.DeleteModel(
            name='CourseOffer',
        ),
    ]
