# Generated by Django 4.2.19 on 2026-03-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
