# Generated by Django 4.2.19 on 2026-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='', help_text='Public URL of the profile picture stored in Supabase Storage', max_length=500),
        ),
    ]
