# Generated by Django 4.2.19 on 2026-04-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='', help_text='Public URL of the profile picture stored in Supabase Storage', max_length=500, null=True),
        ),
    ]
