# Generated by Django 4.2.16 on 2026-09-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-student__date_joined',), 'verbose_name': 'Learner', 'verbose_name_plural': 'Learners'},
        ),
    ]
