"""
Django settings for config project.


Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from decouple import config
import dj_database_url
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY", default="o!ld8nrt4vc*h1zoey*wj48x*q0#ss12h=+zh)kk^6b3aygg=!"
)

# Detect if running in a serverless environment (Vercel, Render, etc.)
IS_SERVERLESS = (
    os.environ.get("VERCEL") == "1"
    or os.environ.get("RENDER") == "true"
    or os.environ.get("RAILWAY_ENVIRONMENT") is not None
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=not IS_SERVERLESS, cast=bool)

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "https://*.up.railway.app",
    "https://*.railway.app",
    "https://ueainstitute.onrender.com",
    "https://*.vercel.app",
    "https://rise360-five.vercel.app",
    "https://www.rise360institute.com",
    "https://rise360institute.com",
]

# Tell Django it's secure behind Railway/Render proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Fix CSRF cookie mismatch behind proxy (Railway / Render)
# Only enforce secure cookies in production (not locally)
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# FIX: Use DB-backed sessions instead of signed_cookies.
# signed_cookies has a 4KB browser limit — exceeding it silently drops the
# entire session and logs the user out mid-practice.
# DB sessions store session data server-side; only a small session key
# lives in the browser cookie, so the size limit is never hit.
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Render dynamic hostname support
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# change the default user models to our custom model
AUTH_USER_MODEL = "accounts.User"

# Application definition

DJANGO_APPS = [
    "modeltranslation",  # Translation
    # "jet.dashboard",  # Disabled on Vercel — queries DB at cold start → 8s timeout
    # "jet",            # Disabled on Vercel — same reason
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Third party apps
THIRD_PARTY_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "django_filters",
    "import_export",
    "anymail",
    "axes",
]

# Custom apps
PROJECT_APPS = [
    "core.apps.CoreConfig",
    "accounts.apps.AccountsConfig",
    "course.apps.CourseConfig",
    "search.apps.SearchConfig",
    # EA Exam Prep Apps
    "ea_exam.apps.EaExamConfig",
    "ea_analytics",
    "ea_content",
]

# Combine all apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # whitenoise to serve static files — must be 2nd
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # 'django.template.context_processors.i18n',
                # 'django.template.context_processors.media',
                # 'django.template.context_processors.static',
                # 'django.template.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# Update database configuration from $DATABASE_URL if provided
db_url = config("DATABASE_URL", default="")
if db_url:
    # Use conn_max_age=0 in local DEBUG mode to avoid exhausting connection pools (e.g. Supabase 15 max connections limit)
    conn_max_age = config("CONN_MAX_AGE", default=0 if DEBUG else 60, cast=int)
    db_from_env = dj_database_url.parse(db_url, conn_max_age=conn_max_age)
    db_from_env.setdefault("OPTIONS", {})
    db_from_env["OPTIONS"]["connect_timeout"] = 5
    DATABASES['default'].update(db_from_env)

# https://docs.djangoproject.com/en/stable/ref/settings/#std:setting-DEFAULT_AUTO_FIELD
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation — empty list allows users to register with easy/simple passwords
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/


def gettext(s):
    return s


LANGUAGES = (
    ("en", gettext("English")),
    ("fr", gettext("French")),
    ("es", gettext("Spanish")),
    ("ru", gettext("Russia")),
)

LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "/static/"
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "public"),
]
# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Media files config
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Supabase Storage bucket name for user-uploaded media
SUPABASE_MEDIA_BUCKET = config("SUPABASE_MEDIA_BUCKET", default="media-files")

# In production/serverless the filesystem is read-only (Vercel / Render).
# Route all media uploads through Supabase Storage when running in serverless OR when DEBUG is False,
# provided SUPABASE_URL is configured.
if (IS_SERVERLESS or not DEBUG) and config("SUPABASE_URL", default=""):
    DEFAULT_FILE_STORAGE = "core.storage.SupabaseMediaStorage"

# -----------------------------------
# E-mail configuration (Brevo HTTP API - works on Railway)
# Railway blocks all outbound SMTP (port 587/465), so we use Brevo API over HTTPS

BREVO_API_KEY = config("BREVO_API_KEY", default="")

if BREVO_API_KEY:
    # Production: use Brevo HTTP API (never touches SMTP)
    EMAIL_BACKEND = "anymail.backends.sendinblue.EmailBackend"
    ANYMAIL = {
        "SENDINBLUE_API_KEY": BREVO_API_KEY,
    }
else:
    # Local development fallback: print emails to console
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_FROM_ADDRESS = config("EMAIL_FROM_ADDRESS", default="noreply@uea.up.railway.app")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_FROM_ADDRESS)

# crispy config
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = "/en/accounts/profile/"
LOGOUT_REDIRECT_URL = "/"

# Password reset link timeout (3 days in seconds)
PASSWORD_RESET_TIMEOUT = 259200

# Domain used in password reset emails – must match the live site
# Django's PasswordResetView uses request.get_host(), but defining this
# ensures the correct https:// link is always generated.
SITE_DOMAIN = config('SITE_DOMAIN', default='uea.up.railway.app')

# Strip payment config
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")

# Supabase Storage Config for Private Ebooks
SUPABASE_URL = config("SUPABASE_URL", default="")
SUPABASE_SERVICE_KEY = config("SUPABASE_SERVICE_KEY", default="")

# LOGGING
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#logging
# See https://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "handlers": {
        "null": {"class": "logging.NullHandler"},
        "console": {"class": "logging.StreamHandler", "level": "ERROR"},
    },
    "root": {
        "handlers": ["console"],
        "level": "ERROR",
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "django.db.backends": {"handlers": ["null"], "level": "CRITICAL", "propagate": False},
    },
}

# ------------------------------------------------------------------------------
# SECURITY HARDENING HEADERS & SETTINGS
# ------------------------------------------------------------------------------
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
# FIX: Do not expire sessions on browser close — users doing long practice
# sessions were being logged out when they switched tabs or the OS closed
# the background browser context.
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# FIX: Extended to 8 hours so users are not logged out mid-exam.
# The subscription middleware now uses its own timestamp-based TTL
# instead of calling set_expiry() which was resetting this to 5 minutes.
SESSION_COOKIE_AGE = 28800  # 8 hours

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# WhiteNoise configuration
# Use CompressedStaticFilesStorage (no manifest) to avoid missing-file errors on Vercel
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

STUDENT_ID_PREFIX = config("STUDENT_ID_PREFIX", "ugr")
LECTURER_ID_PREFIX = config("LECTURER_ID_PREFIX", "lec")


# Constants
YEARS = (
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
    (6, "6"),
)

BACHELOR_DEGREE = "Bachelor"
MASTER_DEGREE = "Master"

LEVEL_CHOICES = (
    (BACHELOR_DEGREE, _("Bachelor Degree")),
    (MASTER_DEGREE, _("Master Degree")),
)

FIRST = "First"
SECOND = "Second"
THIRD = "Third"

SEMESTER_CHOICES = (
    (FIRST, _("First")),
    (SECOND, _("Second")),
    (THIRD, _("Third")),
)

# Brute Force Protection (django-axes)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_LOCKOUT_PARAMETERS = ['ip_address', 'username']
AXES_RESET_ON_SUCCESS = True

# Razorpay Credentials
RAZORPAY_KEY_ID = config("RAZORPAY_KEY_ID", default="rzp_test_1234567890abcdef")
RAZORPAY_KEY_SECRET = config("RAZORPAY_KEY_SECRET", default="1234567890abcdef12345678")

