# Generated by Django 4.2.19 on 2026-03-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainaccuracy',
            name='prometric_weight',
        ),
    ]
