# Generated by Django 4.2.19 on 2026-03-24 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EADomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prometric_weight', models.DecimalField(decimal_places=2, help_text='Official Prometric weight percentage (e.g., 17.5)', max_digits=5)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'EA Domain',
                'verbose_name_plural': 'EA Domains',
                'ordering': ['part', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EAPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'Part 1 – Individuals'), (2, 'Part 2 – Businesses'), (3, 'Part 3 – Representation, Practices & Procedures')], unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_questions', models.PositiveIntegerField(default=100)),
                ('time_limit_minutes', models.PositiveIntegerField(default=210)),
            ],
            options={
                'verbose_name': 'EA Part',
                'verbose_name_plural': 'EA Parts',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='EATopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='ea_exam.eadomain')),
            ],
            options={
                'verbose_name': 'EA Topic',
                'verbose_name_plural': 'EA Topics',
                'ordering': ['domain', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EASubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='ea_exam.eatopic')),
            ],
            options={
                'verbose_name': 'EA Subtopic',
            },
        ),
        migrations.CreateModel(
            name='EAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The main question text')),
                ('explanation', models.TextField(blank=True, help_text='Why is the correct answer correct?')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('review', 'Under Review')], default='active', max_length=10)),
                ('year_appeared', models.PositiveSmallIntegerField(blank=True, help_text='Tax year this question first appeared', null=True)),
                ('irs_pub_ref', models.CharField(blank=True, help_text="IRS Publication reference, e.g. 'Pub 17, Chapter 4'", max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ea_exam.eadomain')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ea_exam.eapart')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.easubtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='ea_exam.eatopic')),
            ],
            options={
                'verbose_name': 'EA Question',
                'verbose_name_plural': 'EA Questions',
                'ordering': ['part', 'domain', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='EAExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('practice', 'Practice Mode'), ('exam', 'Exam Simulation')], default='practice', max_length=10)),
                ('question_order', models.TextField(default='')),
                ('question_list', models.TextField(default='')),
                ('user_answers', models.JSONField(default=dict)),
                ('flagged_questions', models.JSONField(default=list)),
                ('num_questions', models.PositiveSmallIntegerField(default=10)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_correct', models.PositiveSmallIntegerField(default=0)),
                ('domain', models.ForeignKey(blank=True, help_text='If set, practice is filtered to this domain', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.eadomain')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ea_exam.eapart')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.eatopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ea_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EA Exam Session',
                'verbose_name_plural': 'EA Exam Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='eadomain',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='ea_exam.eapart'),
        ),
        migrations.CreateModel(
            name='EAChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, help_text='Why this choice is right/wrong')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ea_exam.eaquestion')),
            ],
            options={
                'verbose_name': 'EA Choice',
                'ordering': ['order'],
            },
        ),
    ]
