# Generated by Django 4.2.19 on 2026-03-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0003_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eadomain',
            name='prometric_weight',
        ),        migrations.RemoveField(
            model_name='eaquestion',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='eatopic',
            name='ebook_external_url',
            field=models.URLField(blank=True, help_text='External link (IRS.gov, PDF CDN, etc.)'),
        ),
        migrations.AddField(
            model_name='eatopic',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='ea_ebooks/'),
        ),
        migrations.AddField(
            model_name='eatopic',
            name='video_external_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo link'),
        ),
        migrations.AddField(
            model_name='eatopic',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='ea_videos/'),
        ),
        migrations.DeleteModel(
            name='EASubtopic',
        ),
    ]
