# Generated by Django 4.2.19 on 2026-03-30 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ea_exam', '0004_remove_eadomain_prometric_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='last_accessed_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ea_exam.eatopic'),
        ),
        migrations.CreateModel(
            name='UserTopicReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='ea_exam.eatopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Topic Read Status',
                'verbose_name_plural': 'User Topic Read Statuses',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
