# Generated by Django 4.2.19 on 2026-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0005_userprogress_last_accessed_topic_usertopicreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatopic',
            name='supabase_pdf_path',
            field=models.CharField(blank=True, default='', help_text="Path in Supabase 'ea-ebooks' private bucket", max_length=500),
        ),
    ]
