# Generated by Django 4.2.16 on 2026-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0006_eatopic_supabase_pdf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='eaquestion',
            name='choice_1',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Choice 1'),
        ),
        migrations.AddField(
            model_name='eaquestion',
            name='choice_1_correct',
            field=models.BooleanField(default=False, verbose_name='Choice 1 Correct'),
        ),
        migrations.AddField(
            model_name='eaquestion',
            name='choice_2',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Choice 2'),
        ),
        migrations.AddField(
            model_name='eaquestion',
            name='choice_2_correct',
            field=models.BooleanField(default=False, verbose_name='Choice 2 Correct'),
        ),
        migrations.AddField(
            model_name='eaquestion',
            name='choice_3',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Choice 3'),
        ),
        migrations.AddField(
            model_name='eaquestion',
            name='choice_3_correct',
            field=models.BooleanField(default=False, verbose_name='Choice 3 Correct'),
        ),
        migrations.AddField(
            model_name='eaquestion',
            name='choice_4',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Choice 4'),
        ),
        migrations.AddField(
            model_name='eaquestion',
            name='choice_4_correct',
            field=models.BooleanField(default=False, verbose_name='Choice 4 Correct'),
        ),
    ]
