# Generated by Django 4.2.16 on 2026-07-01 07:43

from django.db import migrations

def migrate_choices_to_questions(apps, schema_editor):
    EAQuestion = apps.get_model('ea_exam', 'EAQuestion')
    EAChoice = apps.get_model('ea_exam', 'EAChoice')
    EAExamSession = apps.get_model('ea_exam', 'EAExamSession')

    # Step 1: Pre-fetch all choices ordered by order and id
    all_choices = list(EAChoice.objects.all().order_by('order', 'id'))
    choices_by_question = {}
    for choice in all_choices:
        choices_by_question.setdefault(choice.question_id, []).append(choice)

    choice_id_to_key_map = {}
    questions_to_update = []

    # Step 2: Update all questions in memory
    for question in EAQuestion.objects.all():
        choices = choices_by_question.get(question.id, [])
        
        # Populate choice columns
        if len(choices) > 0:
            question.choice_1 = choices[0].choice_text
            question.choice_1_correct = choices[0].is_correct
            choice_id_to_key_map[choices[0].id] = "choice1"
            
        if len(choices) > 1:
            question.choice_2 = choices[1].choice_text
            question.choice_2_correct = choices[1].is_correct
            choice_id_to_key_map[choices[1].id] = "choice2"
            
        if len(choices) > 2:
            question.choice_3 = choices[2].choice_text
            question.choice_3_correct = choices[2].is_correct
            choice_id_to_key_map[choices[2].id] = "choice3"
            
        if len(choices) > 3:
            question.choice_4 = choices[3].choice_text
            question.choice_4_correct = choices[3].is_correct
            choice_id_to_key_map[choices[3].id] = "choice4"
            
        questions_to_update.append(question)

    if questions_to_update:
        EAQuestion.objects.bulk_update(questions_to_update, [
            'choice_1', 'choice_2', 'choice_3', 'choice_4',
            'choice_1_correct', 'choice_2_correct', 'choice_3_correct', 'choice_4_correct'
        ], batch_size=100)

    # Step 3: Update exam sessions in memory and bulk save
    sessions_to_update = []
    for session in EAExamSession.objects.all():
        if session.user_answers:
            updated_answers = {}
            modified = False
            for qid_str, cid in session.user_answers.items():
                try:
                    cid_int = int(cid)
                    if cid_int in choice_id_to_key_map:
                        updated_answers[qid_str] = choice_id_to_key_map[cid_int]
                        modified = True
                    else:
                        updated_answers[qid_str] = cid
                except (ValueError, TypeError):
                    updated_answers[qid_str] = cid
            if modified:
                session.user_answers = updated_answers
                sessions_to_update.append(session)

    if sessions_to_update:
        EAExamSession.objects.bulk_update(sessions_to_update, ['user_answers'], batch_size=100)

def rollback_choices(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0007_eaquestion_choice_1_eaquestion_choice_1_correct_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_choices_to_questions, rollback_choices),
    ]
