# Generated by Django 4.2.16 on 2026-07-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0008_auto_20260701_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EAChoice',
        ),
    ]
