# Generated by Django 4.2.16 on 2026-08-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0009_delete_eachoice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eaexamsession',
            index=models.Index(fields=['user', 'part'], name='ea_exam_eae_user_id_484d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='eaexamsession',
            index=models.Index(fields=['user', '-started_at'], name='ea_exam_eae_user_id_7f8904_idx'),
        ),
        migrations.AddIndex(
            model_name='eaquestion',
            index=models.Index(fields=['part', 'status'], name='ea_exam_eaq_part_id_348700_idx'),
        ),
        migrations.AddIndex(
            model_name='eaquestion',
            index=models.Index(fields=['domain', 'status'], name='ea_exam_eaq_domain__943b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='eaquestion',
            index=models.Index(fields=['topic', 'status'], name='ea_exam_eaq_topic_i_6622d4_idx'),
        ),
        migrations.AddIndex(
            model_name='usertopicreadstatus',
            index=models.Index(fields=['user', 'topic'], name='ea_exam_use_user_id_d54b5c_idx'),
        ),
    ]
