# Generated by Django 4.2.16 on 2026-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0010_eaexamsession_ea_exam_eae_user_id_484d0d_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eapart',
            options={'ordering': ['number'], 'verbose_name': 'Learning Topic / Module', 'verbose_name_plural': 'Learning Topics / Modules'},
        ),
        migrations.AlterField(
            model_name='eapart',
            name='name',
            field=models.CharField(help_text='Topic name, e.g. MS Excel, Bookkeeping, Canadian Taxation', max_length=200),
        ),
        migrations.AlterField(
            model_name='eapart',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='Display order / module number', unique=True),
        ),
        migrations.AlterField(
            model_name='eapart',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
