# Generated by Django 4.2.16 on 2026-09-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0011_alter_eapart_options_alter_eapart_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eapart',
            name='time_limit_minutes',
        ),
        migrations.RemoveField(
            model_name='eapart',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='eaquestion',
            name='irs_pub_ref',
        ),
        migrations.RemoveField(
            model_name='eaquestion',
            name='version',
        ),
        migrations.RemoveField(
            model_name='eaquestion',
            name='year_appeared',
        ),
        migrations.RemoveField(
            model_name='eatopic',
            name='ebook_external_url',
        ),
    ]
