# Generated by Django 4.2.16 on 2026-09-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0012_remove_eapart_time_limit_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eaquestion',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='eaquestion',
            name='part',
        ),
        migrations.RemoveField(
            model_name='eaquestion',
            name='topic',
        ),
        migrations.AlterUniqueTogether(
            name='questionusernote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionusernote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionusernote',
            name='user',
        ),
        migrations.DeleteModel(
            name='EAExamSession',
        ),
        migrations.DeleteModel(
            name='EAQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionUserNote',
        ),
    ]
