# Generated by Django 4.2.16 on 2026-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_exam', '0013_remove_eaquestion_domain_remove_eaquestion_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eapart',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this module is active and accessible to students.'),
        ),
    ]
